# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dto/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dto/common.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_options=b'\n\023com.nowcoder.ut.idlP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64to/common.proto\x12\x13\x63om.nowcoder.ut.idl\">\n\x0c\x42uryNumStats\x12.\n\x08\x62ury_num\x18\x01 \x03(\x0b\x32\x1c.com.nowcoder.ut.idl.BuryNum\"F\n\x07\x42uryNum\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x0b\n\x03loc\x18\x02 \x01(\x05\x12\x0f\n\x07\x63orrect\x18\x03 \x01(\x08\x12\x0b\n\x03num\x18\x04 \x01(\x03\"G\n\x0cScreenDetect\x12\x15\n\rpredict_class\x18\x01 \x01(\t\x12\x12\n\nspam_class\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"*\n\tDebugInfo\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x10\n\x08track_id\x18\x02 \x01(\tB\x17\n\x13\x63om.nowcoder.ut.idlP\x00\x62\x06proto3'
)




_BURYNUMSTATS = _descriptor.Descriptor(
  name='BuryNumStats',
  full_name='com.nowcoder.ut.idl.BuryNumStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bury_num', full_name='com.nowcoder.ut.idl.BuryNumStats.bury_num', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=103,
)


_BURYNUM = _descriptor.Descriptor(
  name='BuryNum',
  full_name='com.nowcoder.ut.idl.BuryNum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform', full_name='com.nowcoder.ut.idl.BuryNum.platform', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loc', full_name='com.nowcoder.ut.idl.BuryNum.loc', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correct', full_name='com.nowcoder.ut.idl.BuryNum.correct', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='com.nowcoder.ut.idl.BuryNum.num', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=175,
)


_SCREENDETECT = _descriptor.Descriptor(
  name='ScreenDetect',
  full_name='com.nowcoder.ut.idl.ScreenDetect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predict_class', full_name='com.nowcoder.ut.idl.ScreenDetect.predict_class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spam_class', full_name='com.nowcoder.ut.idl.ScreenDetect.spam_class', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='com.nowcoder.ut.idl.ScreenDetect.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=248,
)


_DEBUGINFO = _descriptor.Descriptor(
  name='DebugInfo',
  full_name='com.nowcoder.ut.idl.DebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='com.nowcoder.ut.idl.DebugInfo.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='com.nowcoder.ut.idl.DebugInfo.track_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=292,
)

_BURYNUMSTATS.fields_by_name['bury_num'].message_type = _BURYNUM
DESCRIPTOR.message_types_by_name['BuryNumStats'] = _BURYNUMSTATS
DESCRIPTOR.message_types_by_name['BuryNum'] = _BURYNUM
DESCRIPTOR.message_types_by_name['ScreenDetect'] = _SCREENDETECT
DESCRIPTOR.message_types_by_name['DebugInfo'] = _DEBUGINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuryNumStats = _reflection.GeneratedProtocolMessageType('BuryNumStats', (_message.Message,), {
  'DESCRIPTOR' : _BURYNUMSTATS,
  '__module__' : 'dto.common_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.BuryNumStats)
  })
_sym_db.RegisterMessage(BuryNumStats)

BuryNum = _reflection.GeneratedProtocolMessageType('BuryNum', (_message.Message,), {
  'DESCRIPTOR' : _BURYNUM,
  '__module__' : 'dto.common_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.BuryNum)
  })
_sym_db.RegisterMessage(BuryNum)

ScreenDetect = _reflection.GeneratedProtocolMessageType('ScreenDetect', (_message.Message,), {
  'DESCRIPTOR' : _SCREENDETECT,
  '__module__' : 'dto.common_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.ScreenDetect)
  })
_sym_db.RegisterMessage(ScreenDetect)

DebugInfo = _reflection.GeneratedProtocolMessageType('DebugInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGINFO,
  '__module__' : 'dto.common_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.DebugInfo)
  })
_sym_db.RegisterMessage(DebugInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
