# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discuss_rec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discuss_rec.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_options=b'\n\023com.nowcoder.ut.idlP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64iscuss_rec.proto\x12\x13\x63om.nowcoder.ut.idl\"\x9b\x01\n\x12\x44iscussUserFeature\x12\x11\n\tedu_level\x18\x01 \x01(\t\x12\x11\n\twork_info\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x11\n\twork_time\x18\x04 \x01(\x05\x12\x16\n\x0ehist_entity_id\x18\x05 \x03(\t\x12\x0f\n\x07max_len\x18\x06 \x01(\x05\x12\x13\n\x0bhist_career\x18\x07 \x03(\t\"\xe5\x01\n\x12\x44iscussItemFeature\x12\x16\n\x0elikenumber_var\x18\x01 \x01(\x05\x12\x16\n\x0eviewnumber_var\x18\x02 \x01(\x05\x12\x17\n\x0freplynumber_var\x18\x03 \x01(\x05\x12\x10\n\x08ge_score\x18\x04 \x01(\x02\x12\x10\n\x08wv_score\x18\x05 \x01(\x02\x12\x11\n\tlan_score\x18\x06 \x01(\x02\x12\x0b\n\x03\x63tr\x18\x07 \x01(\x02\x12\x11\n\tentity_id\x18\x08 \x01(\t\x12\x11\n\ttaxonomy1\x18\t \x01(\t\x12\x0c\n\x04\x66orm\x18\n \x01(\t\x12\x0e\n\x06\x63\x61reer\x18\x0b \x01(\t\"\x92\x01\n\x12\x44iscussRankRequest\x12=\n\x0cuser_feature\x18\x01 \x01(\x0b\x32\'.com.nowcoder.ut.idl.DiscussUserFeature\x12=\n\x0citem_feature\x18\x02 \x03(\x0b\x32\'.com.nowcoder.ut.idl.DiscussItemFeatureB\x17\n\x13\x63om.nowcoder.ut.idlP\x00\x62\x06proto3'
)




_DISCUSSUSERFEATURE = _descriptor.Descriptor(
  name='DiscussUserFeature',
  full_name='com.nowcoder.ut.idl.DiscussUserFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='edu_level', full_name='com.nowcoder.ut.idl.DiscussUserFeature.edu_level', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_info', full_name='com.nowcoder.ut.idl.DiscussUserFeature.work_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='com.nowcoder.ut.idl.DiscussUserFeature.gender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_time', full_name='com.nowcoder.ut.idl.DiscussUserFeature.work_time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_entity_id', full_name='com.nowcoder.ut.idl.DiscussUserFeature.hist_entity_id', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_len', full_name='com.nowcoder.ut.idl.DiscussUserFeature.max_len', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_career', full_name='com.nowcoder.ut.idl.DiscussUserFeature.hist_career', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=198,
)


_DISCUSSITEMFEATURE = _descriptor.Descriptor(
  name='DiscussItemFeature',
  full_name='com.nowcoder.ut.idl.DiscussItemFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='likenumber_var', full_name='com.nowcoder.ut.idl.DiscussItemFeature.likenumber_var', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='viewnumber_var', full_name='com.nowcoder.ut.idl.DiscussItemFeature.viewnumber_var', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replynumber_var', full_name='com.nowcoder.ut.idl.DiscussItemFeature.replynumber_var', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ge_score', full_name='com.nowcoder.ut.idl.DiscussItemFeature.ge_score', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wv_score', full_name='com.nowcoder.ut.idl.DiscussItemFeature.wv_score', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lan_score', full_name='com.nowcoder.ut.idl.DiscussItemFeature.lan_score', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctr', full_name='com.nowcoder.ut.idl.DiscussItemFeature.ctr', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='com.nowcoder.ut.idl.DiscussItemFeature.entity_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taxonomy1', full_name='com.nowcoder.ut.idl.DiscussItemFeature.taxonomy1', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='form', full_name='com.nowcoder.ut.idl.DiscussItemFeature.form', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='career', full_name='com.nowcoder.ut.idl.DiscussItemFeature.career', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=430,
)


_DISCUSSRANKREQUEST = _descriptor.Descriptor(
  name='DiscussRankRequest',
  full_name='com.nowcoder.ut.idl.DiscussRankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_feature', full_name='com.nowcoder.ut.idl.DiscussRankRequest.user_feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_feature', full_name='com.nowcoder.ut.idl.DiscussRankRequest.item_feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=579,
)

_DISCUSSRANKREQUEST.fields_by_name['user_feature'].message_type = _DISCUSSUSERFEATURE
_DISCUSSRANKREQUEST.fields_by_name['item_feature'].message_type = _DISCUSSITEMFEATURE
DESCRIPTOR.message_types_by_name['DiscussUserFeature'] = _DISCUSSUSERFEATURE
DESCRIPTOR.message_types_by_name['DiscussItemFeature'] = _DISCUSSITEMFEATURE
DESCRIPTOR.message_types_by_name['DiscussRankRequest'] = _DISCUSSRANKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscussUserFeature = _reflection.GeneratedProtocolMessageType('DiscussUserFeature', (_message.Message,), {
  'DESCRIPTOR' : _DISCUSSUSERFEATURE,
  '__module__' : 'discuss_rec_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.DiscussUserFeature)
  })
_sym_db.RegisterMessage(DiscussUserFeature)

DiscussItemFeature = _reflection.GeneratedProtocolMessageType('DiscussItemFeature', (_message.Message,), {
  'DESCRIPTOR' : _DISCUSSITEMFEATURE,
  '__module__' : 'discuss_rec_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.DiscussItemFeature)
  })
_sym_db.RegisterMessage(DiscussItemFeature)

DiscussRankRequest = _reflection.GeneratedProtocolMessageType('DiscussRankRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCUSSRANKREQUEST,
  '__module__' : 'discuss_rec_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.DiscussRankRequest)
  })
_sym_db.RegisterMessage(DiscussRankRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
