# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: end_page_similar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='end_page_similar.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_options=b'\n\023com.nowcoder.ut.idlP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x65nd_page_similar.proto\x12\x13\x63om.nowcoder.ut.idl\"\x89\x02\n\x19\x45ndPageSimilarUserFeature\x12\x17\n\x0fyear_salary_min\x18\x01 \x01(\x03\x12\x17\n\x0fyear_salary_max\x18\x02 \x01(\x03\x12\x1a\n\x12work_status_detail\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x14\n\x0cschool_major\x18\x05 \x01(\t\x12\x12\n\nlogin_type\x18\x06 \x01(\x05\x12\x13\n\x0bhonor_score\x18\x07 \x01(\x02\x12\x13\n\x0bhonor_level\x18\x08 \x01(\x05\x12\x0e\n\x06gender\x18\t \x01(\t\x12\x11\n\tedu_level\x18\n \x01(\t\x12\x19\n\x11\x63\x61reer_preference\x18\x0b \x01(\t\"\xb4\x01\n\x19\x45ndPageSimilarItemFeature\x12\x11\n\tentity_id\x18\x01 \x01(\x03\x12\x11\n\titem_type\x18\x02 \x01(\t\x12\x13\n\x0bmoment_type\x18\x03 \x01(\x05\x12\x0b\n\x03\x63tr\x18\x04 \x01(\x02\x12\x13\n\x0blike_number\x18\x05 \x01(\x02\x12\x0f\n\x07ugc_cnt\x18\x06 \x01(\x02\x12\x14\n\x0creply_number\x18\x07 \x01(\x02\x12\x13\n\x0bview_number\x18\x08 \x01(\x02\"*\n\tDebugInfo\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x10\n\x08track_id\x18\x02 \x01(\t\"\x8b\x02\n\x15\x45ndPageSimilarRequest\x12<\n\x04user\x18\x01 \x01(\x0b\x32..com.nowcoder.ut.idl.EndPageSimilarUserFeature\x12\x41\n\tpage_item\x18\x02 \x01(\x0b\x32..com.nowcoder.ut.idl.EndPageSimilarItemFeature\x12=\n\x05items\x18\x03 \x03(\x0b\x32..com.nowcoder.ut.idl.EndPageSimilarItemFeature\x12\x32\n\ndebug_info\x18\x04 \x01(\x0b\x32\x1e.com.nowcoder.ut.idl.DebugInfo\"[\n\x16\x45ndPageSimilarResponse\x12\r\n\x05score\x18\x01 \x03(\x02\x12\x32\n\ndebug_info\x18\x02 \x01(\x0b\x32\x1e.com.nowcoder.ut.idl.DebugInfoB\x17\n\x13\x63om.nowcoder.ut.idlP\x00\x62\x06proto3'
)




_ENDPAGESIMILARUSERFEATURE = _descriptor.Descriptor(
  name='EndPageSimilarUserFeature',
  full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='year_salary_min', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.year_salary_min', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='year_salary_max', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.year_salary_max', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_status_detail', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.work_status_detail', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='school_major', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.school_major', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='login_type', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.login_type', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='honor_score', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.honor_score', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='honor_level', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.honor_level', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.gender', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edu_level', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.edu_level', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='career_preference', full_name='com.nowcoder.ut.idl.EndPageSimilarUserFeature.career_preference', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=313,
)


_ENDPAGESIMILARITEMFEATURE = _descriptor.Descriptor(
  name='EndPageSimilarItemFeature',
  full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.entity_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_type', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.item_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='moment_type', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.moment_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctr', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.ctr', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='like_number', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.like_number', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ugc_cnt', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.ugc_cnt', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reply_number', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.reply_number', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='view_number', full_name='com.nowcoder.ut.idl.EndPageSimilarItemFeature.view_number', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=496,
)


_DEBUGINFO = _descriptor.Descriptor(
  name='DebugInfo',
  full_name='com.nowcoder.ut.idl.DebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='com.nowcoder.ut.idl.DebugInfo.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='com.nowcoder.ut.idl.DebugInfo.track_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=540,
)


_ENDPAGESIMILARREQUEST = _descriptor.Descriptor(
  name='EndPageSimilarRequest',
  full_name='com.nowcoder.ut.idl.EndPageSimilarRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='com.nowcoder.ut.idl.EndPageSimilarRequest.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page_item', full_name='com.nowcoder.ut.idl.EndPageSimilarRequest.page_item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='com.nowcoder.ut.idl.EndPageSimilarRequest.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug_info', full_name='com.nowcoder.ut.idl.EndPageSimilarRequest.debug_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=810,
)


_ENDPAGESIMILARRESPONSE = _descriptor.Descriptor(
  name='EndPageSimilarResponse',
  full_name='com.nowcoder.ut.idl.EndPageSimilarResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='com.nowcoder.ut.idl.EndPageSimilarResponse.score', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug_info', full_name='com.nowcoder.ut.idl.EndPageSimilarResponse.debug_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=812,
  serialized_end=903,
)

_ENDPAGESIMILARREQUEST.fields_by_name['user'].message_type = _ENDPAGESIMILARUSERFEATURE
_ENDPAGESIMILARREQUEST.fields_by_name['page_item'].message_type = _ENDPAGESIMILARITEMFEATURE
_ENDPAGESIMILARREQUEST.fields_by_name['items'].message_type = _ENDPAGESIMILARITEMFEATURE
_ENDPAGESIMILARREQUEST.fields_by_name['debug_info'].message_type = _DEBUGINFO
_ENDPAGESIMILARRESPONSE.fields_by_name['debug_info'].message_type = _DEBUGINFO
DESCRIPTOR.message_types_by_name['EndPageSimilarUserFeature'] = _ENDPAGESIMILARUSERFEATURE
DESCRIPTOR.message_types_by_name['EndPageSimilarItemFeature'] = _ENDPAGESIMILARITEMFEATURE
DESCRIPTOR.message_types_by_name['DebugInfo'] = _DEBUGINFO
DESCRIPTOR.message_types_by_name['EndPageSimilarRequest'] = _ENDPAGESIMILARREQUEST
DESCRIPTOR.message_types_by_name['EndPageSimilarResponse'] = _ENDPAGESIMILARRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EndPageSimilarUserFeature = _reflection.GeneratedProtocolMessageType('EndPageSimilarUserFeature', (_message.Message,), {
  'DESCRIPTOR' : _ENDPAGESIMILARUSERFEATURE,
  '__module__' : 'end_page_similar_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.EndPageSimilarUserFeature)
  })
_sym_db.RegisterMessage(EndPageSimilarUserFeature)

EndPageSimilarItemFeature = _reflection.GeneratedProtocolMessageType('EndPageSimilarItemFeature', (_message.Message,), {
  'DESCRIPTOR' : _ENDPAGESIMILARITEMFEATURE,
  '__module__' : 'end_page_similar_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.EndPageSimilarItemFeature)
  })
_sym_db.RegisterMessage(EndPageSimilarItemFeature)

DebugInfo = _reflection.GeneratedProtocolMessageType('DebugInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGINFO,
  '__module__' : 'end_page_similar_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.DebugInfo)
  })
_sym_db.RegisterMessage(DebugInfo)

EndPageSimilarRequest = _reflection.GeneratedProtocolMessageType('EndPageSimilarRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDPAGESIMILARREQUEST,
  '__module__' : 'end_page_similar_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.EndPageSimilarRequest)
  })
_sym_db.RegisterMessage(EndPageSimilarRequest)

EndPageSimilarResponse = _reflection.GeneratedProtocolMessageType('EndPageSimilarResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDPAGESIMILARRESPONSE,
  '__module__' : 'end_page_similar_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.EndPageSimilarResponse)
  })
_sym_db.RegisterMessage(EndPageSimilarResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
