# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: home_rec_v3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='home_rec_v3.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_options=b'\n\023com.nowcoder.ut.idlP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11home_rec_v3.proto\x12\x13\x63om.nowcoder.ut.idl\"\xb9\x01\n\x15HomeRankV3UserFeature\x12\x16\n\x0e\x65\x64ucation_info\x18\x01 \x01(\t\x12\x11\n\twork_info\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x16\n\x0ehist_entity_id\x18\x04 \x03(\t\x12\x11\n\thist_type\x18\x05 \x03(\t\x12\x0f\n\x07max_len\x18\x06 \x01(\x05\x12\x16\n\x0ehist_taxonomy1\x18\x07 \x03(\t\x12\x11\n\thist_form\x18\x08 \x03(\t\"\xc9\x02\n\x15HomeRankV3ItemFeature\x12\x16\n\x0epostmodule_var\x18\x01 \x01(\t\x12\x18\n\x10\x63ontenttopic_var\x18\x02 \x01(\t\x12\x16\n\x0elikenumber_var\x18\x03 \x01(\x05\x12\x16\n\x0eviewnumber_var\x18\x04 \x01(\x05\x12\x17\n\x0freplynumber_var\x18\x05 \x01(\x05\x12\x16\n\x0e\x63irclename_var\x18\x06 \x01(\t\x12\x17\n\x0f\x63ontentmode_var\x18\x07 \x01(\t\x12\x0c\n\x04type\x18\x08 \x01(\t\x12\x10\n\x08ge_score\x18\t \x01(\x02\x12\x10\n\x08wv_score\x18\n \x01(\x02\x12\x11\n\tlan_score\x18\x0b \x01(\x02\x12\x0b\n\x03\x63tr\x18\x0c \x01(\x02\x12\x11\n\tentity_id\x18\r \x01(\t\x12\x11\n\ttaxonomy1\x18\x0e \x01(\t\x12\x0c\n\x04\x66orm\x18\x0f \x01(\t\"\x97\x01\n\x11HomeRankV3Request\x12@\n\x0cuser_feature\x18\x01 \x01(\x0b\x32*.com.nowcoder.ut.idl.HomeRankV3UserFeature\x12@\n\x0citem_feature\x18\x02 \x03(\x0b\x32*.com.nowcoder.ut.idl.HomeRankV3ItemFeatureB\x17\n\x13\x63om.nowcoder.ut.idlP\x00\x62\x06proto3'
)




_HOMERANKV3USERFEATURE = _descriptor.Descriptor(
  name='HomeRankV3UserFeature',
  full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='education_info', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.education_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_info', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.work_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.gender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_entity_id', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.hist_entity_id', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_type', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.hist_type', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_len', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.max_len', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_taxonomy1', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.hist_taxonomy1', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_form', full_name='com.nowcoder.ut.idl.HomeRankV3UserFeature.hist_form', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=228,
)


_HOMERANKV3ITEMFEATURE = _descriptor.Descriptor(
  name='HomeRankV3ItemFeature',
  full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='postmodule_var', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.postmodule_var', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contenttopic_var', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.contenttopic_var', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='likenumber_var', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.likenumber_var', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='viewnumber_var', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.viewnumber_var', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replynumber_var', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.replynumber_var', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='circlename_var', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.circlename_var', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentmode_var', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.contentmode_var', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ge_score', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.ge_score', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wv_score', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.wv_score', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lan_score', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.lan_score', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctr', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.ctr', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.entity_id', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taxonomy1', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.taxonomy1', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='form', full_name='com.nowcoder.ut.idl.HomeRankV3ItemFeature.form', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=560,
)


_HOMERANKV3REQUEST = _descriptor.Descriptor(
  name='HomeRankV3Request',
  full_name='com.nowcoder.ut.idl.HomeRankV3Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_feature', full_name='com.nowcoder.ut.idl.HomeRankV3Request.user_feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_feature', full_name='com.nowcoder.ut.idl.HomeRankV3Request.item_feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=714,
)

_HOMERANKV3REQUEST.fields_by_name['user_feature'].message_type = _HOMERANKV3USERFEATURE
_HOMERANKV3REQUEST.fields_by_name['item_feature'].message_type = _HOMERANKV3ITEMFEATURE
DESCRIPTOR.message_types_by_name['HomeRankV3UserFeature'] = _HOMERANKV3USERFEATURE
DESCRIPTOR.message_types_by_name['HomeRankV3ItemFeature'] = _HOMERANKV3ITEMFEATURE
DESCRIPTOR.message_types_by_name['HomeRankV3Request'] = _HOMERANKV3REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HomeRankV3UserFeature = _reflection.GeneratedProtocolMessageType('HomeRankV3UserFeature', (_message.Message,), {
  'DESCRIPTOR' : _HOMERANKV3USERFEATURE,
  '__module__' : 'home_rec_v3_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeRankV3UserFeature)
  })
_sym_db.RegisterMessage(HomeRankV3UserFeature)

HomeRankV3ItemFeature = _reflection.GeneratedProtocolMessageType('HomeRankV3ItemFeature', (_message.Message,), {
  'DESCRIPTOR' : _HOMERANKV3ITEMFEATURE,
  '__module__' : 'home_rec_v3_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeRankV3ItemFeature)
  })
_sym_db.RegisterMessage(HomeRankV3ItemFeature)

HomeRankV3Request = _reflection.GeneratedProtocolMessageType('HomeRankV3Request', (_message.Message,), {
  'DESCRIPTOR' : _HOMERANKV3REQUEST,
  '__module__' : 'home_rec_v3_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeRankV3Request)
  })
_sym_db.RegisterMessage(HomeRankV3Request)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
