# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: home_rec_attention.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='home_rec_attention.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_options=b'\n\023com.nowcoder.ut.idlP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18home_rec_attention.proto\x12\x13\x63om.nowcoder.ut.idl\"\x8b\x01\n\x12HomeAttUserFeature\x12\x16\n\x0e\x65\x64ucation_info\x18\x01 \x01(\t\x12\x11\n\twork_info\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x16\n\x0ehist_entity_id\x18\x04 \x03(\t\x12\x11\n\thist_type\x18\x05 \x03(\t\x12\x0f\n\x07max_len\x18\x06 \x01(\x05\"\xa5\x02\n\x12HomeAttItemFeature\x12\x16\n\x0epostmodule_var\x18\x01 \x01(\t\x12\x18\n\x10\x63ontenttopic_var\x18\x02 \x01(\t\x12\x16\n\x0elikenumber_var\x18\x03 \x01(\x05\x12\x16\n\x0eviewnumber_var\x18\x04 \x01(\x05\x12\x17\n\x0freplynumber_var\x18\x05 \x01(\x05\x12\x16\n\x0e\x63irclename_var\x18\x06 \x01(\t\x12\x17\n\x0f\x63ontentmode_var\x18\x07 \x01(\t\x12\x0c\n\x04type\x18\x08 \x01(\t\x12\x10\n\x08ge_score\x18\t \x01(\x02\x12\x10\n\x08wv_score\x18\n \x01(\x02\x12\x11\n\tlan_score\x18\x0b \x01(\x02\x12\x0b\n\x03\x63tr\x18\x0c \x01(\x02\x12\x11\n\tentity_id\x18\r \x01(\t\"\x98\x01\n\x18HomeAttentionRankRequest\x12=\n\x0cuser_feature\x18\x01 \x01(\x0b\x32\'.com.nowcoder.ut.idl.HomeAttUserFeature\x12=\n\x0citem_feature\x18\x02 \x03(\x0b\x32\'.com.nowcoder.ut.idl.HomeAttItemFeatureB\x17\n\x13\x63om.nowcoder.ut.idlP\x00\x62\x06proto3'
)




_HOMEATTUSERFEATURE = _descriptor.Descriptor(
  name='HomeAttUserFeature',
  full_name='com.nowcoder.ut.idl.HomeAttUserFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='education_info', full_name='com.nowcoder.ut.idl.HomeAttUserFeature.education_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_info', full_name='com.nowcoder.ut.idl.HomeAttUserFeature.work_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='com.nowcoder.ut.idl.HomeAttUserFeature.gender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_entity_id', full_name='com.nowcoder.ut.idl.HomeAttUserFeature.hist_entity_id', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist_type', full_name='com.nowcoder.ut.idl.HomeAttUserFeature.hist_type', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_len', full_name='com.nowcoder.ut.idl.HomeAttUserFeature.max_len', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=189,
)


_HOMEATTITEMFEATURE = _descriptor.Descriptor(
  name='HomeAttItemFeature',
  full_name='com.nowcoder.ut.idl.HomeAttItemFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='postmodule_var', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.postmodule_var', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contenttopic_var', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.contenttopic_var', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='likenumber_var', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.likenumber_var', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='viewnumber_var', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.viewnumber_var', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replynumber_var', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.replynumber_var', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='circlename_var', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.circlename_var', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentmode_var', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.contentmode_var', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ge_score', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.ge_score', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wv_score', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.wv_score', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lan_score', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.lan_score', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctr', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.ctr', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='com.nowcoder.ut.idl.HomeAttItemFeature.entity_id', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=485,
)


_HOMEATTENTIONRANKREQUEST = _descriptor.Descriptor(
  name='HomeAttentionRankRequest',
  full_name='com.nowcoder.ut.idl.HomeAttentionRankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_feature', full_name='com.nowcoder.ut.idl.HomeAttentionRankRequest.user_feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_feature', full_name='com.nowcoder.ut.idl.HomeAttentionRankRequest.item_feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=640,
)

_HOMEATTENTIONRANKREQUEST.fields_by_name['user_feature'].message_type = _HOMEATTUSERFEATURE
_HOMEATTENTIONRANKREQUEST.fields_by_name['item_feature'].message_type = _HOMEATTITEMFEATURE
DESCRIPTOR.message_types_by_name['HomeAttUserFeature'] = _HOMEATTUSERFEATURE
DESCRIPTOR.message_types_by_name['HomeAttItemFeature'] = _HOMEATTITEMFEATURE
DESCRIPTOR.message_types_by_name['HomeAttentionRankRequest'] = _HOMEATTENTIONRANKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HomeAttUserFeature = _reflection.GeneratedProtocolMessageType('HomeAttUserFeature', (_message.Message,), {
  'DESCRIPTOR' : _HOMEATTUSERFEATURE,
  '__module__' : 'home_rec_attention_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeAttUserFeature)
  })
_sym_db.RegisterMessage(HomeAttUserFeature)

HomeAttItemFeature = _reflection.GeneratedProtocolMessageType('HomeAttItemFeature', (_message.Message,), {
  'DESCRIPTOR' : _HOMEATTITEMFEATURE,
  '__module__' : 'home_rec_attention_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeAttItemFeature)
  })
_sym_db.RegisterMessage(HomeAttItemFeature)

HomeAttentionRankRequest = _reflection.GeneratedProtocolMessageType('HomeAttentionRankRequest', (_message.Message,), {
  'DESCRIPTOR' : _HOMEATTENTIONRANKREQUEST,
  '__module__' : 'home_rec_attention_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeAttentionRankRequest)
  })
_sym_db.RegisterMessage(HomeAttentionRankRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
