# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ut-caesar-api/src/main/proto/home_rec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ut-caesar-api/src/main/proto/home_rec.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_pb=_b('\n+ut-caesar-api/src/main/proto/home_rec.proto\x12\x13\x63om.nowcoder.ut.idl\"L\n\x0fHomeUserFeature\x12\x16\n\x0e\x65\x64ucation_info\x18\x01 \x01(\t\x12\x11\n\twork_info\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\"\x82\x02\n\x0fHomeItemFeature\x12\x16\n\x0epostmodule_var\x18\x01 \x01(\t\x12\x18\n\x10\x63ontenttopic_var\x18\x02 \x01(\t\x12\x16\n\x0elikenumber_var\x18\x03 \x01(\x05\x12\x16\n\x0eviewnumber_var\x18\x04 \x01(\x05\x12\x17\n\x0freplynumber_var\x18\x05 \x01(\x05\x12\x16\n\x0e\x63irclename_var\x18\x06 \x01(\t\x12\x17\n\x0f\x63ontentmode_var\x18\x07 \x01(\t\x12\x0c\n\x04type\x18\x08 \x01(\t\x12\x10\n\x08ge_score\x18\t \x01(\x02\x12\x10\n\x08wv_score\x18\n \x01(\x02\x12\x11\n\tlan_score\x18\x0b \x01(\x02\"\x89\x01\n\x0fHomeRankRequest\x12:\n\x0cuser_feature\x18\x01 \x01(\x0b\x32$.com.nowcoder.ut.idl.HomeUserFeature\x12:\n\x0citem_feature\x18\x02 \x03(\x0b\x32$.com.nowcoder.ut.idl.HomeItemFeatureB\x17\n\x13\x63om.nowcoder.ut.idlP\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HOMEUSERFEATURE = _descriptor.Descriptor(
  name='HomeUserFeature',
  full_name='com.nowcoder.ut.idl.HomeUserFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='education_info', full_name='com.nowcoder.ut.idl.HomeUserFeature.education_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='work_info', full_name='com.nowcoder.ut.idl.HomeUserFeature.work_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='com.nowcoder.ut.idl.HomeUserFeature.gender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=144,
)


_HOMEITEMFEATURE = _descriptor.Descriptor(
  name='HomeItemFeature',
  full_name='com.nowcoder.ut.idl.HomeItemFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='postmodule_var', full_name='com.nowcoder.ut.idl.HomeItemFeature.postmodule_var', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contenttopic_var', full_name='com.nowcoder.ut.idl.HomeItemFeature.contenttopic_var', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='likenumber_var', full_name='com.nowcoder.ut.idl.HomeItemFeature.likenumber_var', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='viewnumber_var', full_name='com.nowcoder.ut.idl.HomeItemFeature.viewnumber_var', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replynumber_var', full_name='com.nowcoder.ut.idl.HomeItemFeature.replynumber_var', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='circlename_var', full_name='com.nowcoder.ut.idl.HomeItemFeature.circlename_var', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contentmode_var', full_name='com.nowcoder.ut.idl.HomeItemFeature.contentmode_var', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.nowcoder.ut.idl.HomeItemFeature.type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ge_score', full_name='com.nowcoder.ut.idl.HomeItemFeature.ge_score', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wv_score', full_name='com.nowcoder.ut.idl.HomeItemFeature.wv_score', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lan_score', full_name='com.nowcoder.ut.idl.HomeItemFeature.lan_score', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=405,
)


_HOMERANKREQUEST = _descriptor.Descriptor(
  name='HomeRankRequest',
  full_name='com.nowcoder.ut.idl.HomeRankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_feature', full_name='com.nowcoder.ut.idl.HomeRankRequest.user_feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_feature', full_name='com.nowcoder.ut.idl.HomeRankRequest.item_feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=545,
)

_HOMERANKREQUEST.fields_by_name['user_feature'].message_type = _HOMEUSERFEATURE
_HOMERANKREQUEST.fields_by_name['item_feature'].message_type = _HOMEITEMFEATURE
DESCRIPTOR.message_types_by_name['HomeUserFeature'] = _HOMEUSERFEATURE
DESCRIPTOR.message_types_by_name['HomeItemFeature'] = _HOMEITEMFEATURE
DESCRIPTOR.message_types_by_name['HomeRankRequest'] = _HOMERANKREQUEST

HomeUserFeature = _reflection.GeneratedProtocolMessageType('HomeUserFeature', (_message.Message,), dict(
  DESCRIPTOR = _HOMEUSERFEATURE,
  __module__ = 'ut_caesar_api.src.main.proto.home_rec_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeUserFeature)
  ))
_sym_db.RegisterMessage(HomeUserFeature)

HomeItemFeature = _reflection.GeneratedProtocolMessageType('HomeItemFeature', (_message.Message,), dict(
  DESCRIPTOR = _HOMEITEMFEATURE,
  __module__ = 'ut_caesar_api.src.main.proto.home_rec_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeItemFeature)
  ))
_sym_db.RegisterMessage(HomeItemFeature)

HomeRankRequest = _reflection.GeneratedProtocolMessageType('HomeRankRequest', (_message.Message,), dict(
  DESCRIPTOR = _HOMERANKREQUEST,
  __module__ = 'ut_caesar_api.src.main.proto.home_rec_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.HomeRankRequest)
  ))
_sym_db.RegisterMessage(HomeRankRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.nowcoder.ut.idlP\000'))
# @@protoc_insertion_point(module_scope)
