# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predict_request.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15predict_request.proto\"]\n\x0e\x44iscussFeature\x12\x10\n\x08ge_score\x18\x01 \x01(\x02\x12\x10\n\x08wv_score\x18\x02 \x01(\x02\x12\x11\n\tlan_score\x18\x03 \x01(\x02\x12\x14\n\x0c\x65xposure_num\x18\x04 \x01(\x05\"e\n\x15\x44iscussPredictRequest\x12(\n\x0f\x64iscuss_feature\x18\x01 \x03(\x0b\x32\x0f.DiscussFeature\x12\x15\n\x08trace_id\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_trace_idb\x06proto3'
)




_DISCUSSFEATURE = _descriptor.Descriptor(
  name='DiscussFeature',
  full_name='DiscussFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ge_score', full_name='DiscussFeature.ge_score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wv_score', full_name='DiscussFeature.wv_score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lan_score', full_name='DiscussFeature.lan_score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exposure_num', full_name='DiscussFeature.exposure_num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=118,
)


_DISCUSSPREDICTREQUEST = _descriptor.Descriptor(
  name='DiscussPredictRequest',
  full_name='DiscussPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='discuss_feature', full_name='DiscussPredictRequest.discuss_feature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='DiscussPredictRequest.trace_id', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_trace_id', full_name='DiscussPredictRequest._trace_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=120,
  serialized_end=221,
)

_DISCUSSPREDICTREQUEST.fields_by_name['discuss_feature'].message_type = _DISCUSSFEATURE
_DISCUSSPREDICTREQUEST.oneofs_by_name['_trace_id'].fields.append(
  _DISCUSSPREDICTREQUEST.fields_by_name['trace_id'])
_DISCUSSPREDICTREQUEST.fields_by_name['trace_id'].containing_oneof = _DISCUSSPREDICTREQUEST.oneofs_by_name['_trace_id']
DESCRIPTOR.message_types_by_name['DiscussFeature'] = _DISCUSSFEATURE
DESCRIPTOR.message_types_by_name['DiscussPredictRequest'] = _DISCUSSPREDICTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscussFeature = _reflection.GeneratedProtocolMessageType('DiscussFeature', (_message.Message,), {
  'DESCRIPTOR' : _DISCUSSFEATURE,
  '__module__' : 'predict_request_pb2'
  # @@protoc_insertion_point(class_scope:DiscussFeature)
  })
_sym_db.RegisterMessage(DiscussFeature)

DiscussPredictRequest = _reflection.GeneratedProtocolMessageType('DiscussPredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCUSSPREDICTREQUEST,
  '__module__' : 'predict_request_pb2'
  # @@protoc_insertion_point(class_scope:DiscussPredictRequest)
  })
_sym_db.RegisterMessage(DiscussPredictRequest)


# @@protoc_insertion_point(module_scope)
