# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: read_history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='read_history.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12read_history.proto\x12\x13\x63om.nowcoder.ut.idl\"%\n\x04item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"7\n\x0cread_history\x12\'\n\x04list\x18\x01 \x03(\x0b\x32\x19.com.nowcoder.ut.idl.itemb\x06proto3'
)




_ITEM = _descriptor.Descriptor(
  name='item',
  full_name='com.nowcoder.ut.idl.item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.nowcoder.ut.idl.item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.nowcoder.ut.idl.item.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=80,
)


_READ_HISTORY = _descriptor.Descriptor(
  name='read_history',
  full_name='com.nowcoder.ut.idl.read_history',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='com.nowcoder.ut.idl.read_history.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=137,
)

_READ_HISTORY.fields_by_name['list'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['item'] = _ITEM
DESCRIPTOR.message_types_by_name['read_history'] = _READ_HISTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

item = _reflection.GeneratedProtocolMessageType('item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'read_history_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.item)
  })
_sym_db.RegisterMessage(item)

read_history = _reflection.GeneratedProtocolMessageType('read_history', (_message.Message,), {
  'DESCRIPTOR' : _READ_HISTORY,
  '__module__' : 'read_history_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.read_history)
  })
_sym_db.RegisterMessage(read_history)


# @@protoc_insertion_point(module_scope)
