# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_ltr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='search_ltr.proto',
  package='com.nowcoder.ut.idl',
  syntax='proto3',
  serialized_options=b'\n\023com.nowcoder.ut.idlP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10search_ltr.proto\x12\x13\x63om.nowcoder.ut.idl\"E\n\x0cQueryFeature\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tquery_len\x18\x02 \x01(\x03\x12\x13\n\x0bsearch_type\x18\x03 \x01(\x03\"\xc3\x04\n\x0bItemFeature\x12\x0f\n\x07item_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\x03\x12\x13\n\x0b\x66rom_create\x18\x03 \x01(\x02\x12\x13\n\x0b\x66rom_update\x18\x04 \x01(\x02\x12\x10\n\x08view_cnt\x18\x05 \x01(\x03\x12\x13\n\x0b\x63omment_cnt\x18\x06 \x01(\x03\x12\x11\n\ttitle_len\x18\x07 \x01(\x03\x12\x10\n\x08tags_len\x18\x08 \x01(\x03\x12\x13\n\x0b\x63ontent_len\x18\t \x01(\x03\x12\x14\n\x0c\x64ocument_len\x18\n \x01(\x03\x12\x12\n\nbm25_title\x18\x0b \x01(\x02\x12\x11\n\tbm25_tags\x18\x0c \x01(\x02\x12\x14\n\x0c\x62m25_content\x18\r \x01(\x02\x12\x15\n\rbm25_document\x18\x0e \x01(\x02\x12\x11\n\tjac_title\x18\x0f \x01(\x02\x12\x10\n\x08jac_tags\x18\x10 \x01(\x02\x12\x13\n\x0bjac_content\x18\x11 \x01(\x02\x12\x14\n\x0cjac_document\x18\x12 \x01(\x02\x12 \n\x18\x63ompletely_contain_title\x18\x13 \x01(\x03\x12\"\n\x1a\x63ompletely_contain_content\x18\x14 \x01(\x03\x12\x1c\n\x14occurrence_num_title\x18\x15 \x01(\x03\x12\x1e\n\x16occurrence_num_content\x18\x16 \x01(\x03\x12 \n\x18segment_occurrence_title\x18\x17 \x01(\x03\x12\"\n\x1asegment_occurrence_content\x18\x18 \x01(\x03\"\x85\x01\n\x10SearchLTRRequest\x12\x38\n\rquery_feature\x18\x01 \x01(\x0b\x32!.com.nowcoder.ut.idl.QueryFeature\x12\x37\n\ritem_features\x18\x02 \x03(\x0b\x32 .com.nowcoder.ut.idl.ItemFeature\"#\n\x11SearchLTRResponse\x12\x0e\n\x06scores\x18\x01 \x03(\x02\x42\x17\n\x13\x63om.nowcoder.ut.idlP\x00\x62\x06proto3'
)




_QUERYFEATURE = _descriptor.Descriptor(
  name='QueryFeature',
  full_name='com.nowcoder.ut.idl.QueryFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='com.nowcoder.ut.idl.QueryFeature.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_len', full_name='com.nowcoder.ut.idl.QueryFeature.query_len', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search_type', full_name='com.nowcoder.ut.idl.QueryFeature.search_type', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=110,
)


_ITEMFEATURE = _descriptor.Descriptor(
  name='ItemFeature',
  full_name='com.nowcoder.ut.idl.ItemFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='com.nowcoder.ut.idl.ItemFeature.item_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_type', full_name='com.nowcoder.ut.idl.ItemFeature.content_type', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_create', full_name='com.nowcoder.ut.idl.ItemFeature.from_create', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_update', full_name='com.nowcoder.ut.idl.ItemFeature.from_update', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='view_cnt', full_name='com.nowcoder.ut.idl.ItemFeature.view_cnt', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment_cnt', full_name='com.nowcoder.ut.idl.ItemFeature.comment_cnt', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_len', full_name='com.nowcoder.ut.idl.ItemFeature.title_len', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags_len', full_name='com.nowcoder.ut.idl.ItemFeature.tags_len', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_len', full_name='com.nowcoder.ut.idl.ItemFeature.content_len', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='document_len', full_name='com.nowcoder.ut.idl.ItemFeature.document_len', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bm25_title', full_name='com.nowcoder.ut.idl.ItemFeature.bm25_title', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bm25_tags', full_name='com.nowcoder.ut.idl.ItemFeature.bm25_tags', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bm25_content', full_name='com.nowcoder.ut.idl.ItemFeature.bm25_content', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bm25_document', full_name='com.nowcoder.ut.idl.ItemFeature.bm25_document', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jac_title', full_name='com.nowcoder.ut.idl.ItemFeature.jac_title', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jac_tags', full_name='com.nowcoder.ut.idl.ItemFeature.jac_tags', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jac_content', full_name='com.nowcoder.ut.idl.ItemFeature.jac_content', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jac_document', full_name='com.nowcoder.ut.idl.ItemFeature.jac_document', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completely_contain_title', full_name='com.nowcoder.ut.idl.ItemFeature.completely_contain_title', index=18,
      number=19, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completely_contain_content', full_name='com.nowcoder.ut.idl.ItemFeature.completely_contain_content', index=19,
      number=20, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='occurrence_num_title', full_name='com.nowcoder.ut.idl.ItemFeature.occurrence_num_title', index=20,
      number=21, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='occurrence_num_content', full_name='com.nowcoder.ut.idl.ItemFeature.occurrence_num_content', index=21,
      number=22, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segment_occurrence_title', full_name='com.nowcoder.ut.idl.ItemFeature.segment_occurrence_title', index=22,
      number=23, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segment_occurrence_content', full_name='com.nowcoder.ut.idl.ItemFeature.segment_occurrence_content', index=23,
      number=24, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=692,
)


_SEARCHLTRREQUEST = _descriptor.Descriptor(
  name='SearchLTRRequest',
  full_name='com.nowcoder.ut.idl.SearchLTRRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_feature', full_name='com.nowcoder.ut.idl.SearchLTRRequest.query_feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_features', full_name='com.nowcoder.ut.idl.SearchLTRRequest.item_features', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=695,
  serialized_end=828,
)


_SEARCHLTRRESPONSE = _descriptor.Descriptor(
  name='SearchLTRResponse',
  full_name='com.nowcoder.ut.idl.SearchLTRResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scores', full_name='com.nowcoder.ut.idl.SearchLTRResponse.scores', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=865,
)

_SEARCHLTRREQUEST.fields_by_name['query_feature'].message_type = _QUERYFEATURE
_SEARCHLTRREQUEST.fields_by_name['item_features'].message_type = _ITEMFEATURE
DESCRIPTOR.message_types_by_name['QueryFeature'] = _QUERYFEATURE
DESCRIPTOR.message_types_by_name['ItemFeature'] = _ITEMFEATURE
DESCRIPTOR.message_types_by_name['SearchLTRRequest'] = _SEARCHLTRREQUEST
DESCRIPTOR.message_types_by_name['SearchLTRResponse'] = _SEARCHLTRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryFeature = _reflection.GeneratedProtocolMessageType('QueryFeature', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFEATURE,
  '__module__' : 'search_ltr_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.QueryFeature)
  })
_sym_db.RegisterMessage(QueryFeature)

ItemFeature = _reflection.GeneratedProtocolMessageType('ItemFeature', (_message.Message,), {
  'DESCRIPTOR' : _ITEMFEATURE,
  '__module__' : 'search_ltr_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.ItemFeature)
  })
_sym_db.RegisterMessage(ItemFeature)

SearchLTRRequest = _reflection.GeneratedProtocolMessageType('SearchLTRRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHLTRREQUEST,
  '__module__' : 'search_ltr_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.SearchLTRRequest)
  })
_sym_db.RegisterMessage(SearchLTRRequest)

SearchLTRResponse = _reflection.GeneratedProtocolMessageType('SearchLTRResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHLTRRESPONSE,
  '__module__' : 'search_ltr_pb2'
  # @@protoc_insertion_point(class_scope:com.nowcoder.ut.idl.SearchLTRResponse)
  })
_sym_db.RegisterMessage(SearchLTRResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
